
### Autenticacion correcta
POST http://192.168.0.7:7777/api/v1/auth/
Content-Type: application/json
Accept: application/json

{
  "username": "lramirez",
  "password": "ABCabc123"
}

### Autenticacion incorrecta
POST http://localhost:7777/api/v1/auth/
Content-Type: application/json
Accept: application/json

{
  "username": "lramirez",
  "password": "ABCabc123"
}

### Autenticacion con valores vacios
POST http://localhost:7777/api/v1/auth/
Content-Type: application/json
Accept: application/json

{
}
################# Consultar usuario

GET http://localhost:7777/api/v1/user/
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJscmFtaXJleiIsInJvbGVzIjpbIkNSRUFSX1VTVUFSSU8iXSwiaXNzIjoidWNiIiwicmVmcmVzaCI6ZmFsc2UsImV4cCI6MTY2Nzk2MTAyN30.RfG54w8p2y5yFTi3K5Ysx6p0Kyai8afEX7VfLWECe4E